version: '3'

services:
  academy:
    build: Academy
    restart: always
    env_file:
      - .docker.env
    ports:
      - '4000:4000'
    extra_hosts:
      - 'dockerhost:172.55.1.1'
  website:
    build: Website
    restart: always
    env_file:
      - .docker.env
    ports:
      - '8000:8000'
    extra_hosts:
      - 'dockerhost:172.55.1.1'
