version: '3'

services:
  academy:
    build: ./Academy
    restart: always
    ports: 
      - 4000:80
    env_file:
      - .docker.env


  website:
    build: ./Website
    restart: always
    ports: 
      - 8000:81
    env_file: .docker.env

